import * as fs from 'fs';
import { Command } from 'commander';
import { YouTubeTranscriptApi } from '../api';
import { GenericProxyConfig, WebshareProxyConfig, ProxyConfig } from '../proxies';
import { FormatterLoader } from '../formatters';
import { TranscriptList, FetchedTranscript } from '../transcripts/models';

export interface CliOptions {
  videoIds?: string[];
  listTranscripts?: boolean;
  languages: string[];
  excludeGenerated?: boolean;
  excludeManuallyCreated?: boolean;
  format: string;
  translate?: string;
  webshareProxyUsername?: string;
  webshareProxyPassword?: string;
  httpProxy?: string;
  httpsProxy?: string;
  cookies?: string;
  verbose?: boolean;
  save?: string;
  batchFile?: string;
  failFast?: boolean;
}

/**
 * CLI class for YouTube Transcript API
 */
export class YouTubeTranscriptCli {
  private program: Command;

  constructor() {
    this.program = new Command();
    this.setupCommands();
  }

  /**
   * Setup CLI commands and options
   */
  private setupCommands(): void {
    this.program
      .name('youtube-transcript-api')
      .description(
        'This is a JavaScript API which allows you to get the transcripts/subtitles for a given YouTube video. ' +
        'It also works for automatically generated subtitles and it does not require a headless browser, ' +
        'like other selenium based solutions do!'
      )
      .version(process.env.PACKAGE_VERSION || '0.0.0')
      .argument('[video-ids...]', 'List of YouTube video IDs')
      .option(
        '--list-transcripts',
        'This will list the languages in which the given videos are available in.'
      )
      .option(
        '--languages <languages...>',
        'A list of language codes in a descending priority. For example, if this is set to "de en" it will ' +
        'first try to fetch the german transcript (de) and then fetch the english transcript (en) if it fails ' +
        'to do so. As I can\'t provide a complete list of all working language codes with full certainty, you ' +
        'may have to play around with the language codes a bit, to find the one which is working for you!',
        ['en']
      )
      .option(
        '--exclude-generated',
        'If this flag is set transcripts which have been generated by YouTube will not be retrieved.'
      )
      .option(
        '--exclude-manually-created',
        'If this flag is set transcripts which have been manually created will not be retrieved.'
      )
      .option(
        '--format <format>',
        'Output format for transcripts',
        'pretty'
      )
      .option(
        '--translate <language>',
        'The language code for the language you want this transcript to be translated to. Use the ' +
        '--list-transcripts feature to find out which languages are translatable and which translation ' +
        'languages are available.'
      )
      .option(
        '--webshare-proxy-username <username>',
        'Specify your Webshare "Proxy Username" found at https://dashboard.webshare.io/proxy/settings'
      )
      .option(
        '--webshare-proxy-password <password>',
        'Specify your Webshare "Proxy Password" found at https://dashboard.webshare.io/proxy/settings'
      )
      .option(
        '--http-proxy <url>',
        'Use the specified HTTP proxy.'
      )
      .option(
        '--https-proxy <url>',
        'Use the specified HTTPS proxy.'
      )
      .option(
        '--cookies <file>',
        'Path to a cookie file (Netscape or JSON format) for authentication (e.g. age-restricted videos).'
      )
      .option(
        '--verbose',
        'Print debug information to stderr.'
      )
      .option(
        '--save <file>',
        'Write output to a file instead of stdout.'
      )
      .option(
        '--batch-file <file>',
        'Read video IDs from a file (one per line, lines starting with # are ignored).'
      )
      .option(
        '--fail-fast',
        'Exit immediately on the first error instead of continuing with remaining videos.'
      )
      .action(this.handleCommand.bind(this));
  }

  /**
   * Handle the main command
   */
  private async handleCommand(videoIds: string[], options: CliOptions): Promise<void> {
    try {
      // Commander.js passes arguments differently - check if videoIds is actually the options
      if (Array.isArray(videoIds) && videoIds.length > 0 && typeof videoIds[0] === 'string' && !videoIds[0].startsWith('--')) {
        // videoIds is correctly passed
      } else if (options && Array.isArray(options.videoIds)) {
        // Arguments might be in options
        videoIds = options.videoIds;
      } else if (!options.batchFile) {
        // Try to get from process.argv, skipping flags and their values
        const args = process.argv.slice(2);
        const FLAGS_WITH_VALUES = new Set([
          '--languages', '--format', '--translate',
          '--webshare-proxy-username', '--webshare-proxy-password',
          '--http-proxy', '--https-proxy',
          '--cookies', '--save', '--batch-file',
        ]);
        const videoIdArgs: string[] = [];
        for (let i = 0; i < args.length; i++) {
          const arg = args[i]!;
          if (arg.startsWith('--')) {
            if (FLAGS_WITH_VALUES.has(arg)) {
              i++; // skip the flag's value
            }
            continue;
          }
          videoIdArgs.push(arg);
        }
        if (videoIdArgs.length > 0) {
          videoIds = videoIdArgs;
        }
      }
      
      // Load video IDs from batch file if specified (before empty check)
      if (options.batchFile) {
        if (!fs.existsSync(options.batchFile)) {
          console.error(`Error: Batch file not found: ${options.batchFile}`);
          process.exit(1);
        }
        const fileContent = fs.readFileSync(options.batchFile, 'utf-8');
        const fileIds = fileContent
          .split('\n')
          .map(line => line.trim())
          .filter(line => line && !line.startsWith('#'));
        this.log(`Loaded ${fileIds.length} video IDs from batch file: ${options.batchFile}`, options);
        videoIds = [...(videoIds || []), ...fileIds];
      }

      if (!videoIds || videoIds.length === 0) {
        this.program.help();
        return;
      }

      if (options.excludeManuallyCreated && options.excludeGenerated) {
        console.error(
          'Error: Cannot use both --exclude-manually-created and --exclude-generated together.\n' +
          'This would exclude all transcripts.'
        );
        process.exit(1);
      }

      const proxyConfig = this.createProxyConfig(options);
      if (options.verbose && proxyConfig) {
        this.log(`Using proxy: ${proxyConfig.constructor.name}`, options);
      }

      const apiOptions = options.cookies ? { cookiePath: options.cookies } : undefined;
      if (options.cookies) {
        this.log(`Loading cookies from: ${options.cookies}`, options);
      }
      const api = new YouTubeTranscriptApi(proxyConfig, undefined, apiOptions);

      const results: (TranscriptList | FetchedTranscript)[] = [];
      const errors: Error[] = [];

      for (const videoId of videoIds) {
        try {
          this.log(`Fetching transcript for: ${videoId}`, options);
          if (options.listTranscripts) {
            const transcriptList = await api.list(videoId);
            results.push(transcriptList);
          } else {
            const transcript = await this.fetchTranscript(api, videoId, options);
            results.push(transcript);
          }
          this.log(`Successfully fetched: ${videoId}`, options);
        } catch (error) {
          this.log(`Error for ${videoId}: ${(error as Error).message}`, options);
          errors.push(error as Error);
          if (options.failFast) {
            break;
          }
        }
      }

      this.outputResults(results, errors, options);

      if (options.failFast && errors.length > 0) {
        process.exit(1);
      }
    } catch (error) {
      console.error('Error:', error);
      process.exit(1);
    }
  }

  /**
   * Create proxy configuration from options
   */
  private createProxyConfig(options: CliOptions): ProxyConfig | undefined {
    if (options.webshareProxyUsername || options.webshareProxyPassword) {
      return new WebshareProxyConfig(
        options.webshareProxyUsername || '',
        options.webshareProxyPassword || ''
      );
    }

    if (options.httpProxy || options.httpsProxy) {
      return new GenericProxyConfig(options.httpProxy, options.httpsProxy);
    }

    return undefined;
  }

  /**
   * Fetch transcript based on options
   */
  private async fetchTranscript(
    api: YouTubeTranscriptApi,
    videoId: string,
    options: CliOptions
  ): Promise<FetchedTranscript> {
    const transcriptList = await api.list(videoId);
    let transcript;

    if (options.excludeManuallyCreated) {
      transcript = transcriptList.findGeneratedTranscript(options.languages);
    } else if (options.excludeGenerated) {
      transcript = transcriptList.findManuallyCreatedTranscript(options.languages);
    } else {
      transcript = transcriptList.findTranscript(options.languages);
    }

    if (options.translate) {
      transcript = transcript.translate(options.translate);
    }

    return transcript.fetch();
  }

  /**
   * Log verbose output to stderr
   */
  private log(message: string, options: CliOptions): void {
    if (options.verbose) {
      process.stderr.write(`[verbose] ${message}\n`);
    }
  }

  /**
   * Format results and output to stdout or file
   */
  private outputResults(
    results: (TranscriptList | FetchedTranscript)[],
    errors: Error[],
    options: CliOptions
  ): void {
    const outputSections: string[] = [];

    for (const error of errors) {
      outputSections.push(error.message);
    }

    if (results.length > 0) {
      if (options.listTranscripts) {
        for (const result of results) {
          if (result instanceof TranscriptList) {
            outputSections.push(result.toString());
          }
        }
      } else {
        const transcripts = results.filter(r => r instanceof FetchedTranscript) as FetchedTranscript[];
        if (transcripts.length > 0) {
          const formatter = new FormatterLoader().load(options.format);
          outputSections.push(formatter.formatTranscripts(transcripts));
        }
      }
    }

    const content = outputSections.join('\n\n');

    if (options.save) {
      fs.writeFileSync(options.save, content, 'utf-8');
      this.log(`Output written to: ${options.save}`, options);
    } else {
      console.log(content);
    }
  }

  /**
   * Run the CLI
   */
  async run(args: string[]): Promise<void> {
    await this.program.parseAsync(args, { from: 'user' });
  }
}

/**
 * Main CLI entry point
 */
export async function main(): Promise<void> {
  try {
    const cli = new YouTubeTranscriptCli();
    await cli.run(process.argv.slice(2));
  } catch (error) {
    console.error('Error:', error instanceof Error ? error.message : error);
    process.exit(1);
  }
}

// Run if called directly
if (require.main === module) {
  process.on('unhandledRejection', (reason) => {
    console.error('Unhandled Rejection:', reason);
    process.exit(1);
  });
  main();
}
